name:                streamly-bytestring
version:             0.2.0
github:              "psibi/streamly-bytestring"
license:             BSD3
author:              "Sibi Prabakaran"
maintainer:          "sibi@psibi.in"
copyright:           "Sibi Prabakaran"

extra-source-files:
- README.md
- Changelog.md

# Metadata used when publishing your package
synopsis:            Library for streamly and bytestring interoperation.
category:            Streamly, Stream, ByteString

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/psibi/streamly-bytestring#readme>

dependencies:
- base       >= 4.7 && < 5
  # Should have an exact version match as we are depending on Internal modules.
  # Currently compatable with streamly HEAD on GitHub.
- streamly   >= 0.8.0  && < 0.9
- bytestring >= 0.10.0 && < 0.11

when:
  - condition: impl(ghc < 8.1)
    dependencies:
      - base-compat >= 0.11
  - condition: impl(ghc < 8)
    dependencies:
      - transformers >= 0.4

library:
  source-dirs: src
  ghc-options:
  - -Wall
  - -O2

tests:
  sb-test:
    main:                Main.hs
    source-dirs:         test
    ghc-options:
    - -Wall
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - streamly-bytestring
    - streamly
    - hspec
    - hspec-discover
    - bytestring
    - directory
    - filepath
    - quickcheck-instances
    - temporary
    - random

benchmarks:
  sb-benchmark:
    main:                Main.hs
    source-dirs:         benchmark
    ghc-options:
    - -Wall
    - -O2
    dependencies:
    - streamly-bytestring
    - streamly
    - gauge
    - bytestring
    - deepseq
    - random
