resolver: lts-20.14

packages:
- .

extra-deps:
- streamly-core-0.1.0

# Look at https://stackoverflow.com/questions/70045586/could-not-find-module-system-console-mintty-win32-when-compiling-test-framework
flags:
  mintty:
    Win32-2-13-1: false
